export const fakeData = [
  {
    day: "Mon",
    date: "8",
    month: "March",
    patient: "Thompson Riddle Berry",
    visitationType: "Cosultaion",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Afolabi Jemije",
    position: "Head of Operation",
    availability: "Available",
  },
  {
    day: "Tue",
    date: "9",
    month: "March",
    patient: "Jerrisson Riddle Berry",
    visitationType: "Cosultaion",
    time: "2:30pm - 03:00pm",
    doctor: "Dr Okafor Jemije",
    position: "Physiotherapist",
    availability: "Available",
  },
  {
    day: "Wed",
    date: "10",
    month: "March",
    patient: "John Doe",
    visitationType: "Therapy",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Afolabi Jemije",
    position: "Surgeon",
    availability: "Unavailable",
  },
  {
    day: "Thu",
    date: "11",
    month: "March",
    patient: "Thompson Riddle Berry",
    visitationType: "Cosultaion",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Afolabi Jemije",
    position: "Consultant",
    availability: "Available",
  },
  {
    day: "Mon",
    date: "12",
    month: "March",
    patient: "Jane Doe",
    visitationType: "Therapy",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Abdullahi Musa",
    position: "Dentist",
    availability: "Unavailable",
  },
  {
    day: "Wed",
    date: "14",
    month: "March",
    patient: "Jerry Doe",
    visitationType: "Therapy",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Afolabi Akanji",
    position: "Paediatrics",
    availability: "Available",
  },
  {
    day: "Mon",
    date: "17",
    month: "March",
    patient: "Jane Doe",
    visitationType: "Therapy",
    time: "3:00pm - 03:30pm",
    doctor: "Dr Osuofia Makinde",
    position: "Dentist",
    availability: "Available",
  },
  {
    day: "Mon",
    date: "22",
    month: "March",
    patient: "Gary Doe",
    visitationType: "Therapy",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Kufre",
    position: "Surgeon",
    availability: "Available",
  },
  {
    day: "Fri",
    date: "22",
    month: "April",
    patient: "Jane Doe",
    visitationType: "Therapy",
    time: "2:00pm - 02:30pm",
    doctor: "Dr Jibrila Bindow",
    position: "Consultant",
    availability: "Available",
  },
];