export const tableBodyData = [
  {
    name: "Chicken Republic",
    email: "anayo@gmail.com",
    phone: "+23470345678",
    branches: "20",
    status: "Active",
    imageUrl: "",
    dateCreated: "22-01-2022",
    testTaken: "Addiction",
    resident: "Lagos",
    specialty: "Therapist",
    package: "Free"
  },
  {
    name: "Gift Alabo",
    email: "anayo@gmail.com",
    phone: "+23470345678",
    branches: "50",
    status: "Active",
    imageUrl: "",
    dateCreated: "22-01-2022",
    testTaken: "Anxiety",
    resident: "Calabar",
    specialty: "Psychologist",
    package: "Basic"
  },
  {
    name: "Tantalizer",
    email: "anayo@gmail.com",
    phone: "+23470345678",
    branches: "23",
    status: "Active",
    imageUrl: "",
    dateCreated: "22-01-2022",
    testTaken: "Life Stress",
    resident: "Lagos",
    specialty: "Physiotherapist",
    package: "Free",
  },
  {
    name: "PAstor Agbetiii",
    email: "anayo@gmail.com",
    phone: "+23470345678",
    branches: "20",
    status: "Active",
    imageUrl: "",
    dateCreated: "22-01-2022",
    testTaken: "Addiction",
    resident: "Lagos",
    specialty: "Dentist",
    package: "Business"
  },
  {
    name: "Mega Chicken",
    email: "anayo@gmail.com",
    phone: "+23470345678",
    branches: "20",
    status: "Active",
    imageUrl: "",
    dateCreated: "22-01-2022",
    testTaken: "Addiction",
    resident: "Abuja",
    specialty: "Gynaecologist",
    package: "Free"
  },
  {
    name: "Mega Chicken",
    email: "anayo@gmail.com",
    phone: "+23470345678",
    branches: "40",
    status: "Active",
    imageUrl: "",
    dateCreated: "22-01-2022",
    testTaken: "Addiction",
    resident: "Ibadan",
    specialty: "Psychologist",
    package: "Ultimate"
  },
];
